"""Update Message model with is_read and read_at fields

Revision ID: 56960ac31691
Revises: 
Create Date: 2025-11-20 12:41:35.895286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56960ac31691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('read_at')
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
